### ISSUE TITLE
Please include test-driver script from automake

### ISSUE THREAD

**Issue by ginggs** [marcIhm/yabasic#10]
Please run `automake --add-missing` to install the test-driver script so that tests can be run during the build.

**Comment by ginggs** [comment]
I see now that `test-driver` is missing from the `yabasic-2.78.0.tar.gz` and `yabasic-2.78.1.tar.gz` release tarballs, but it was present in earlier releases.

**Comment by marcIhm** [comment]
Hi Graham, thanx for your fixes ! I am just about to prepare a new 
patch-Release (probably nxt weekend); your input will be included.
best regards
Marc

Am 06.09.2017 um 14:19 schrieb Graham Inggs:

**Comment by marcIhm** [comment]
Closing this now.
