### ISSUE TITLE
Paths in tests/io.yab reverted

### ISSUE THREAD

**Issue by ginggs** [marcIhm/yabasic#15]
The recent commit https://github.com/marcIhm/yabasic/commit/7542a9b67b96ce61b268379c9764301059b5f1ef reverted the changes from https://github.com/marcIhm/yabasic/pull/13 and **tests/io.yab** fails again.

**Comment by marcIhm** [comment]
Hi, thanx for reporting ! Will fix this soon. And will include "make 
check" into my Rakefile, so that this kind of regression should not 
happen again.


Am 26.03.2018 um 12:08 schrieb Graham Inggs:

**Comment by marcIhm** [comment]
Hi Graham,

now the tests run fine again. And I have included "make check" into my 
own release-process.

Thanx for reporting !

Best regards,
Marc

Am 26.03.2018 um 12:08 schrieb Graham Inggs:

**Comment by marcIhm** [comment]
Fixed with 2.78.4
