### ISSUE TITLE
Recent change to  bisonflags breaks build

### ISSUE THREAD

**Issue by ginggs** [marcIhm/yabasic#16]
Dropping **-t** from bisonflags here:
https://github.com/marcIhm/yabasic/commit/581eb32b71852a1167cad085a6f2775b38d70e0a#diff-f126dc648bcc8138eeb2e0f40de821b5
breaks the build:
```
main.o: In function `mybind':
./main.c:2335: undefined reference to `yydebug'
main.o: In function `isbound':
./main.c:2157: undefined reference to `yydebug'
main.o: In function `parse_arguments':
./main.c:643: undefined reference to `yydebug'
collect2: error: ld returned 1 exit status
Makefile:649: recipe for target 'yabasic' failed
```

**Comment by ginggs** [comment]
Thanks!  Do you plan to make 2.79.1 available on http://yabasic.de ?

**Comment by marcIhm** [comment]
Yes, next weekend.
Best regards

**Comment by marcIhm** [comment]
Hi Graham, had to increment the patch-level by to to correct an handling 
error during tagging; so the new Version is 2.79.2 (no diff to 2.79.1 
albeit the number).
Both on github and www.yabasic.de

regards
Marc

Am 08.05.2018 um 13:46 schrieb Graham Inggs:

**Comment by marcIhm** [comment]
Forgot to close this; Closing it now.
