### ISSUE TITLE
Error compiling 2.79.2 on Debian: undefined reference to `clock_gettime`

### ISSUE THREAD

**Issue by programandala-net** [marcIhm/yabasic#18]
I use Yabasic 2.78.5, which I compiled without any problem on Raspbian/Debian, some time ago.

Now I want to update to 2.79.2, but `make` throws error "undefined reference to `clock_gettime`" on line 1684 of <function.c>. I've searched all the sources with grep, and there's no other mentions to `clock_gettime`.

Is it a bug or am I missing something?

Thank you.

**Comment by marcIhm** [comment]
Should be fixed in 2.80
