### ISSUE TITLE
Color does not pull through to fonts on grafic window on Windows

### ISSUE THREAD

**Issue by TheMeq** [marcIhm/yabasic#2]
Please see screenshot below. Text does not pull through the color code last assigned.
![capture](https://cloud.githubusercontent.com/assets/7303969/21015439/e5ada25c-bd59-11e6-8e0e-4d35570ee16f.PNG)

**Comment by marcIhm** [comment]
Yes, this does not work under Windows, but does under Linux :-/
will look for the bug ... Thanx !

**Comment by marcIhm** [comment]
Fixed (and tried) for Version 2.77.2 :-)
