### ISSUE TITLE
Suggestion: conditional `do .. loop`

### ISSUE THREAD

**Issue by programandala-net** [marcIhm/yabasic#27]
I had some problems compiling previous versions of Yabasic on ARM (Raspbian OS), but I have compiled and installed 2.82.1 on Intel (Debian OS). So now I can resume a couple of Yabasic projects.

Meanwhile, a have small suggestion for a future version: conditional `do ... loop`, e.g. `do while .. loop`, `do until ... loop`, `do ... loop until` and `do ... loop while`. This control flow structure is supported by Freebasic and other BASICs, beside the other traditional loops.

In my opinion, an advantage of a versatile `do ... loop` is the code is more "regular" and a bit easier to modify, instead of having to use `do ... loop`, `repeat ... until` and `while ... wend`, one for every case.

I don't remember a BASIC that supports conditions at both sides of a `do ... loop`, e.g. `do while ... loop until`, `do until ...loop while`, but it would be useful too, to save some code.

**Comment by marcIhm** [comment]
Thanx for this idea; however, currently I do not see much use in adding more syntax.

**Comment by marcIhm** [comment]
Sorry for my somewhat harsh comment, but I had no other opinion in this direction, so I close the issue.
