### ISSUE TITLE
memory corruption in variable assignments 

### ISSUE THREAD

**Issue by ginggs** [marcIhm/yabasic#5]
From https://bugs.launchpad.net/ubuntu/+source/yabasic/+bug/424602

> A user can corrupt memory, possibly executing code during yabasic's parsing of BASIC files. Using a large value when assigning variables will overflow a buffer and corrupt memory (looks like it could be a pointer on the stack).

The bug report includes an attachment, **191.bas**, containing the following:
`fuzz = AAAAA...`
The letter 'A' was repeated 550 times.

**Comment by marcIhm** [comment]
Hi Graham,
thanx for forwarding this; important (and easy) to correct ...
regards
Marc
