### ISSUE TITLE
Examples about using ffi to access C DLL functions

### ISSUE THREAD

**Issue by 3oheicrw** [marcIhm/yabasic#50]
I have read the document but still don't know how to actually use it.

https://2484.de/yabasic/yabasic.htm#top_ffi

**Comment by 3oheicrw** [comment]
To be more clear I only saw example about extracting information from structures but not pass structures to foreign function. For example if the foreign function expects a structure as the parameters what should I do? It seems your language doesn't support complex data structures via structs at all.

**Comment by marcIhm** [comment]
Well the example for the time-structure goes into this direction: http://2484.de/yabasic/yabasic.htm#idm1749

**Comment by 3oheicrw** [comment]
> Well the example for the time-structure goes into this direction: http://2484.de/yabasic/yabasic.htm#idm1749

Is it really that cumbersome?

**Comment by marcIhm** [comment]
Well yes; it is … after all this is an advanced topic …

 

Von: 3oheicrw ***@***.***> 
Gesendet: Samstag, 9. April 2022 07:51
An: marcIhm/yabasic ***@***.***>
Cc: Marc Ihm ***@***.***>; Comment ***@***.***>
Betreff: Re: [marcIhm/yabasic] Examples about using ffi to access C DLL functions (Issue #50)

 

Well the example for the time-structure goes into this direction: http://2484.de/yabasic/yabasic.htm#idm1749

Is it really that cumbersome?

**Comment by 3oheicrw** [comment]
Having a proper structure support so don't have to deal with memory like currently is much better. Looks like you are hacker doing reverse engineering more than actually just want to use the external C code. Well, you will able to use the C code, but in a time consuming way with lengthy of code. I consider this do not worth the effort.
