### ISSUE TITLE
This is the only implementation of BASIC that use SQRT for square root instead of SQR?

### ISSUE THREAD

**Issue by zpu2tw** [marcIhm/yabasic#52]
I have no idea why my code doesn't work as expected until I guessed what if the square root function is SQRT like on C family languages and it turned out I was right. Why did you choose SQRT instead of SQR from the beginning?

**Comment by marcIhm** [comment]
Hi, this decision is more than 25 years old; can't tell now ...

**Comment by marcIhm** [comment]
And: Sorry for the inconvenience, but this is something I cannot change now without affecting quite a lot of existing users ...
