### ISSUE TITLE
Outdated info about stand-alone programs, in the website FAQ

### ISSUE THREAD

**Issue by programandala-net** [marcIhm/yabasic#54]
This is an issue about the yabasic website, not the code. I hope this is the right place to inform about it. If you prefer other way please let me know.

The [FAQ](http://2484.de/yabasic/content_faq.html) reads there's no way to create stand-alone programs because yabasic does not compile the code into assembly. That is true, but the [binding feature](http://2484.de/yabasic/yabasic.htm#ref_standalone) (which, according to the [log](http://2484.de/yabasic/content_log.html), was added in 2003-01) can create stand-alone programs that in practice work the same way. It seems the FAQ became outdated.

**Comment by programandala-net** [comment]
I just realized the website is part of the repo. Therefore any modification can be proposed by a pull request.

**Comment by marcIhm** [comment]
Just updated the docu; thanx for reporting.
