### ISSUE TITLE
rake error: LoadError: cannot load such file --matrix

### ISSUE THREAD

**Issue by jfhbrook** [marcIhm/yabasic#55]
Hello,

I tried to build yabasic's unix bin locally and I got an error:

```sh
$ rake
rake aborted!
LoadError: cannot load such file -- matrix
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/josh/Software/jfhbrook/yabasic/unix/Rakefile:8:in `<top (required)>'
/home/josh/.local/share/gem/ruby/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

I did some research, and it appears that the "matrix" library got removed from ruby in version 3.1:

https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

My operating system, Fedora, doesn't bundle the matrix gem as a package, so it's not easy to skip over.

I figure there are two strategies here: either ditch the matrix dependency in the Rakefile, or add a Gemfile and directions for installing everything as gems. I can't actually find where `Matrix` is being called in the Rakefile, so I suspect the former is an easy lift - but I'm not sure.

**Comment by marcIhm** [comment]
Well, it looks like you are using the Rakefile; well this is very specialized to my own setup (Windows + WSL2) and not expected to run in any other environment.
The only thing, that is meant to be portable is the usual procedure or ./configure && make
(executed in yabasic/unix/lang). And of course, this works under Unix (Linux) only.
